### ISSUE TITLE
Doesn't work for current Gatsby version

### ISSUE THREAD

**Issue by arthurkhlghatyan** [barskern/gatsby-plugin-pathdata#2]
Hello,

Just checked out the documentation and seems to be very useful plugin,

However it doesn't work with current Gatsby version.

I don't get any errors, just can't query field date for a node.

Here's my configuration code.
`
plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/events`,
        name: `events`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/content/assets`,
        name: `assets`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 1360,
              withWebp: true,
              showCaptions: true,
              quality: 75,
              wrapperStyle: `margin: 7vw 0;`,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          `gatsby-remark-prismjs`,
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
          {
            resolve: 'gatsby-plugin-pathdata',
            options: {
              matchNodeType: 'MarkdownRemark',
              extract: [
                {
                  name: 'date',
                  selector: /.+\/(\d+-\d+-\d+)\/[\w-]+\.md$/,
                  replacer: '$1'
                }
              ]
            }
          },
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-postcss`,
      options: {
        postCssPlugins: [
          require("postcss-easy-import")(),
          require("postcss-custom-properties")({ preserve: false }),
          require("postcss-color-function")(),
          require("autoprefixer")({ browsers: ["last 2 versions"] }),
        ],
      },
    }]
`
I also added config object next to the remark plugin but doesn't work as well.

**Comment by barskern** [comment]
What is "the current" Gatsby version for you? Further could you format the code you posted using the a code block?

Did you make any Markdown files yet? What did you try to do (specifically)?

I appreciate that you report at problem, but the information you have given doesn't really provide enough context to help you. Perhaps [this video](https://www.youtube.com/watch?v=3IEAfyQqUKc) can highlight what I mean in a better way.

**Comment by arthurkhlghatyan** [comment]
@barskern agreed man, not the most informative issue you have ever seen haha,

So let me try to explain more detail.

I'm using 
"gatsby": "^2.4.2",
"gatsby-transformer-remark": "^2.3.12",

Here's my configuration.
`
{
      resolve: 'gatsby-plugin-pathdata',
      options: {
        matchNodeType: 'MarkdownRemark',
        extract: [
          {
            name: 'date',
            selector: /.+\/(\d+-\d+-\d+)\/[\w-]+\.md$/,
            replacer: '$1'
          }
        ]
      }
    }
`

If I got it right, configuration above should be able to extract date field from the post path /events/2018-01-11/hello-world.md

That's what I'm trying to do

Hope it was helpful, let me know if you need anything else.

**Comment by barskern** [comment]
Haha I'm glad you admit it too :smile:

You got it right, so based on what you have sent it should work.

I have not been using this library for a while, but I remember there being a small upgrade when Gatsby changed to v2.0.0. Are you using `v1.1.0` of this plugin?

Have you tried looking in the [interactive GraphQL interface](https://www.gatsbyjs.org/docs/running-queries-with-graphiql/) to query e.g. `allMarkdownRemark` nodes to see if there is anything there?

Besides that I don't really have any other tips. Is your project public? Perhaps you could link to it and I could help you debug?

**Comment by arthurkhlghatyan** [comment]
Hey @barskern,

Sorry for late reply,

Yes, I confirm that I tried to query date field in GraphQL interface and it didn't work.

Here's the project repository https://github.com/arthurkhlghatyan/gatsby-event-timeline/.

as you may probably guess, my goal is to transform date field from path data instead of specifying in markdown files.

Thank you!

**Comment by barskern** [comment]
Your paths don't match the regex. You have e.g. `content/2020-01-01/directory/index.md`, not `content/2020-01-01/index.md`. 

Maybe try the following:

`{ resolve: 'gatsby-plugin-pathdata', options: { matchNodeType: 'MarkdownRemark', extract: [ { name: 'date', selector: /.+\/(\d+-\d+-\d+)\/[\w-]+\/[\w-]+\.md$/, replacer: '$1' } ] } }`

**Comment by arthurkhlghatyan** [comment]
Ah, that's right man, let me try it quickly

**Comment by arthurkhlghatyan** [comment]
Yeah, that works man, awesome, thanks!

And sorry for wasting your time.

Closing the issue now!

**Comment by barskern** [comment]
No worries, I make plenty of similar mistakes myself. I'm glad I could help! Don't hesitate to make an issue again if there is something. 

-------- Opprinnelig melding --------
Fra: Arthur Khlghatyan <notifications@github.com> Dato: 14.01.2020  16:36  (GMT+01:00) Til: barskern/gatsby-plugin-pathdata <gatsby-plugin-pathdata@noreply.github.com> Ko: Ole Martin Ruud <dev@barskern.no>, Mention <mention@noreply.github.com> Emne: Re: [barskern/gatsby-plugin-pathdata] Doesn't work for current Gatsby version (#2) Yeah, that works man, awesome, thanks!
And sorry for wasting your time.
Closing the issue now!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/barskern/gatsby-plugin-pathdata/issues/2?email_source=notifications\u0026email_token=ADSM7BVNF7KUTIXPB3FSG4TQ5XLXTA5CNFSM4KFZEIA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI5BUVY#issuecomment-574233175",
"url": "https://github.com/barskern/gatsby-plugin-pathdata/issues/2?email_source=notifications\u0026email_token=ADSM7BVNF7KUTIXPB3FSG4TQ5XLXTA5CNFSM4KFZEIA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI5BUVY#issuecomment-574233175",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
